### ISSUE TITLE
我的跑不起来，提示报错啦

### ISSUE THREAD

**Issue by ancientry** [dianrong/Hero#1]
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\HP\cer\key'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at createProxyServer (D:\Hero\server\her.js:48:12)
    at her (D:\Hero\server\her.js:172:5)
    at Object.<anonymous> (D:\Hero\server\her.js:176:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

刚刚接触，麻烦您帮忙解答下

**Comment by gpliu** [comment]
需要cd 到server 目录运行node her.js ,https的证书文件是相对地址

**Comment by ancientry** [comment]
更新node之后然后把文件重新放置目录之后，CMD没有报错了，但是http://localhost:3000/提示页面不存在，奇怪了

**Comment by ancientry** [comment]
大牛：您好
可以运行了，按照首页下载hero_moblie报错了，请教您下下
代码如下：
C:\Users\HP>cd /d d:

D:\>cd hero

D:\hero>npm install hero-mobile
D:\hero
`-- hero-mobile@1.0.1

npm WARN enoent ENOENT: no such file or directory, open 'D:\hero\package.json'
npm WARN hero No description
npm WARN hero No repository field.
npm WARN hero No README data
npm WARN hero No license field.

D:\hero>

**Comment by gpliu** [comment]
按照github上的readme做吧，这是最近写的

**Comment by gpliu** [comment]
由于涉及到不同的平台，iOS 用pod，android用marven,js用npm，所以以后npm只维护hero-js的版本。但是我目前没有维护它，目前业务上的事情很忙。

**Comment by ancientry** [comment]
谢谢您回复，在麻烦请教您几个问题：1，我们开发app使用node.js吗？2：若是要开发app就是需要开发iOS 的pod，android的marven.js这两个了吗？还是怎么做呢？3：希望可以有一个教程文档，或者网站，空间主机我可以来提供，因为我发现这个确实很简单，但是就是那里有卡住了，希望可以学习通了，然后加入到hero里面来，谢谢您

**Comment by gpliu** [comment]
nodejs用来做web服务，方便本地调试
iOS你直接把ios的工程放到你自己的工程里面去就好了，pod还是手动都可以。android一样。
下周可以做一些开源的事情。本周确实业务繁忙

**Comment by ancientry** [comment]
好的麻烦您了！加油哈
发自中兴手机邮件客户端

2017年3月22日 14:34于 gpliu <notifications@github.com>写道：

nodejs用来做web服务，方便本地调试
iOS你直接把ios的工程放到你自己的工程里面去就好了，pod还是手动都可以。android一样。
下周可以做一些开源的事情。本周确实业务繁忙

**Comment by ancientry** [comment]
向您咨询下一个事情哈，我们做的app，比如相机，语音，地理位置这些底层api有吗？。

**Comment by gpliu** [comment]
HeroPhotoView可以去取照片，相机
HeroLocationView可以去取位置，
语音我目前的业务没有用到，所以原生里面还没有这个元素，以后会有的

**Comment by ancientry** [comment]
大牛，为啥GIT上面没有代码啥的了，是在更新吗？很期待这款产品呢
